% Generate all the figures in the paper.

reRun = true;  % re-run the simulations, otherwise use existing data files

if reRun, rng('default'); end

figures = {'point_drift1', ...
           'point_drift2', ...
           'point_drift6', ...
           'annulus_drift3', ...
           'inner_disk_drift4', ...
           'inner_disk_drift5', ...
           'inner_disk_drift6', ...
           'inner_disk_correction1', ...
           'inner_disk_correction2', ...
           'inner_disk_correction3', ...
           'point_correction1', ...
           'point_correction2', ...
           'point_correction3'};

% Unused:
           %'annulus_drift1', ...
           %'annulus_drift2', ...
           %'annulus_drift4', ...
           %'inner_disk_drift1', ...
           %'inner_disk_drift2', ...
           %'inner_disk_drift3', ...
           %'point_drift3', ...
           %'point_drift4', ...
           %'point_drift5', ...

for i = 1:length(figures)
	if reRun, tic, end
	generateFigures(figures{i}, reRun)
	if reRun, toc, end
end
