% Generate all the figures in the paper.

reRun = false;  % re-run the simulations, otherwise use existing data files

if reRun, rng('default'); end

figures = {'pt_drift1', ...
           'pt_drift2', ...
           'pt_drift6', ...
           'annulus_drift3', ...
           'inner_disk4', ...
           'inner_disk5', ...
           'inner_disk6', ...
           'inner_disk_correction1', ...
           'inner_disk_correction2', ...
           'inner_disk_correction3', ...
           'pt_correction1', ...
           'pt_correction2', ...
           'pt_correction3'};

% Unused:
           %'annulus_drift1', ...
           %'annulus_drift2', ...
           %'annulus_drift4', ...
           %'inner_disk1', ...
           %'inner_disk2', ...
           %'inner_disk3', ...
           %'pt_drift3', ...
           %'pt_drift4', ...
           %'pt_drift5', ...

for i = 1:length(figures)
	if reRun, tic, end
	generateFigures(figures{i}, reRun)
	if reRun, toc, end
end
